In [443]:
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os

In [444]:
load_dotenv(override=True)
csv_path = os.getenv('CSV_PATH')
csv_path

'wandb_output_2024-12-25-14-14-59.csv'

In [445]:
df = pd.read_csv(csv_path)
df.describe()

,target_character,branch_factor,total_iterations,n_self_alignment,total_timesteps,seed,Evaluation/llm_iteration,Evaluation/acc_imp_perc,Evaluation/exist_imp_perc,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability
count,1150.000000,1150.0,1150.000000,1150.000000,1.150000e+03,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000
mean,1.481739,2.0,7.153043,1.047826,4.895652e+07,3.513913,3.861739,0.136309,0.649101,0.411348,19.330417,2.404957,0.186116,0.149043,0.259884,0.229101,0.503188
std,0.499884,0.0,1.459957,2.035877,6.378531e+06,1.748623,2.051346,0.243482,0.300190,0.341956,11.857983,0.927094,0.384427,0.341443,0.512099,0.336054,0.440814
min,1.000000,2.0,6.000000,0.000000,1.000000e+07,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,2.0,6.000000,0.000000,5.000000e+07,2.000000,2.000000,0.000000,0.466667,0.116667,0.000000,2.333333,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,2.0,6.000000,0.000000,5.000000e+07,4.000000,4.000000,0.011111,0.700000,0.316667,26.000002,2.866667,0.000000,0.000000,0.000000,0.066667,0.466667
75%,2.000000,2.0,9.000000,0.000000,5.000000e+07,5.000000,5.000000,0.133333,0.933333,0.666667,26.400000,3.000000,0.200000,0.100000,0.200000,0.266667,1.000000
max,2.000000,2.0,9.000000,5.000000,5.000000e+07,8.000000,9.000000,1.000000,1.000000,1.000000,33.000000,3.000000,2.000000,2.000000,2.000000,1.000000,1.000000

In [446]:
df.columns

Index(['run_id', 'final_state', 'target_character', 'pe', 'gpt_model',
       'branch_factor', 'exp_name', 'evaluator', 'total_iterations',
       'n_self_alignment', 'feedback_type', 'total_timesteps',
       'reward_feature', 'fewshot', 'problem', 'seed',
       'Evaluation/llm_iteration', 'Evaluation/acc_imp_perc',
       'Evaluation/exist_imp_perc', 'Evaluation/reach_imp_perc',
       'Evaluation/path_length', 'Evaluation/fn_imp_perc',
       'Evaluation/fp_imp_perc', 'Evaluation/tn_imp_perc',
       'Evaluation/tp_imp_perc', 'Evaluation/solvability',
       'Evaluation/playability'],
      dtype='object')

In [456]:
df = df[df['fewshot'] == False]
df = df[df['evaluator'] == 'hr']
df = df[df['feedback_type'] == 'default']
df

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/acc_imp_perc,Evaluation/exist_imp_perc,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability
0,re2wd1xx,pe-cot_it-6_fit-hr_exp-def_t-sce_chr-1_1_s-1,1,cot,gpt-4o,2,def,hr,6,0,...,0.011111,0.533333,0.533333,26.000002,2.566667,0.400000,0.0,0.033333,0.200000,1.000000
1,re2wd1xx,pe-cot_it-6_fit-hr_exp-def_t-sce_chr-1_1_s-1,1,cot,gpt-4o,2,def,hr,6,0,...,0.000000,0.000000,0.000000,26.000000,2.666667,0.333333,0.0,0.000000,0.166667,0.966667
2,re2wd1xx,pe-cot_it-6_fit-hr_exp-def_t-sce_chr-1_1_s-1,1,cot,gpt-4o,2,def,hr,6,0,...,0.033333,0.633333,0.600000,26.214287,2.566667,0.333333,0.0,0.100000,0.166667,0.933333
3,re2wd1xx,pe-cot_it-6_fit-hr_exp-def_t-sce_chr-1_1_s-1,1,cot,gpt-4o,2,def,hr,6,0,...,0.000000,0.600000,0.133333,0.000000,3.000000,0.000000,0.0,0.000000,0.000000,0.000000
4,re2wd1xx,pe-cot_it-6_fit-hr_exp-def_t-sce_chr-1_1_s-1,1,cot,gpt-4o,2,def,hr,6,0,...,0.000000,0.166667,0.000000,0.000000,3.000000,0.000000,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,lnp9nylj,pe-got_it-6_fit-hr_exp-chatgpt4o_t-sce_chr-2_1...,2,got,chatgpt-4o,2,chatgpt4o,hr,6,0,...,0.644444,1.000000,1.000000,26.000002,0.066667,1.000000,0.0,1.933333,1.000000,1.000000
1116,lnp9nylj,pe-got_it-6_fit-hr_exp-chatgpt4o_t-sce_chr-2_1...,2,got,chatgpt-4o,2,chatgpt4o,hr,6,0,...,0.666667,1.000000,1.000000,26.000002,0.000000,1.000000,0.0,2.000000,1.000000,1.000000
1117,lnp9nylj,pe-got_it-6_fit-hr_exp-chatgpt4o_t-sce_chr-2_1...,2,got,chatgpt-4o,2,chatgpt4o,hr,6,0,...,0.666667,1.000000,1.000000,26.000002,0.000000,1.000000,0.0,2.000000,1.000000,1.000000
1118,lnp9nylj,pe-got_it-6_fit-hr_exp-chatgpt4o_t-sce_chr-2_1...,2,got,chatgpt-4o,2,chatgpt4o,hr,6,0,...,0.588889,0.983333,0.983333,26.000002,0.233333,1.000000,0.0,1.766667,1.000000,1.000000
1119,lnp9nylj,pe-got_it-6_fit-hr_exp-chatgpt4o_t-sce_chr-2_1...,2,got,chatgpt-4o,2,chatgpt4o,hr,6,0,...,0.588889,0.983333,0.983333,26.000002,0.233333,1.000000,0.0,1.766667,1.000000,1.000000

In [455]:
df.groupby(['gpt_model', 'pe', 'target_character']).agg({'Evaluation/acc_imp_perc': ['count']})

                                Evaluation/acc_imp_perc
                                                  count
gpt_model  pe  target_character
chatgpt-4o cot 1                                     30
               2                                     24
           got 1                                     24
               2                                     30
           tot 1                                     30
               2                                     30
gpt-4o     cot 1                                     90
               2                                     90
           got 1                                    122
               2                                    105
           tot 1                                    120
               2                                     95

In [449]:
base_df = df[(df['n_self_alignment'] == 0) & (df['Evaluation/llm_iteration'] == 1)]
base_df = base_df.groupby(['gpt_model', 'pe', 'target_character']).agg({'Evaluation/acc_imp_perc': ['mean']})
base_df.columns = ['Base']
base_df = base_df.reset_index()
base_df

NameError: name 'base_dfd' is not defined

In [347]:
sa_df = df[(df['n_self_alignment'] == 5) & (df['Evaluation/llm_iteration'] == 1)]
sa_df = sa_df.groupby(['gpt_model', 'target_character']).agg({'Evaluation/acc_imp_perc': ['mean']})
sa_df.columns = ['+ Self-Alignment']
sa_df = sa_df.reset_index()
sa_df

  gpt_model  target_character  + Self-Alignment
0    gpt-4o                 1          0.069841
1    gpt-4o                 2          0.025926

In [348]:
sa_df_cp = sa_df.copy()
sa_df_cp['gpt_model'] = 'chatgpt-4o'
sa_df_cp['+ Self-Alignment'] = 0
sa_df = pd.concat([sa_df, sa_df_cp])
sa_df

    gpt_model  target_character  + Self-Alignment
0      gpt-4o                 1          0.069841
1      gpt-4o                 2          0.025926
0  chatgpt-4o                 1          0.000000
1  chatgpt-4o                 2          0.000000

In [349]:
fb_df = df[(df['n_self_alignment'] == 0) & (df['Evaluation/llm_iteration'] == 6)]
fb_df = fb_df.groupby(['gpt_model', 'target_character']).agg({'Evaluation/acc_imp_perc': ['mean']})
fb_df.columns = ['+ Feedback']
fb_df = fb_df.reset_index()
fb_df

    gpt_model  target_character  + Feedback
0  chatgpt-4o                 1    0.076190
1  chatgpt-4o                 2    0.327778
2      gpt-4o                 1    0.094643
3      gpt-4o                 2    0.136059

In [350]:
safb_df = df[(df['n_self_alignment'] == 5) & (df['Evaluation/llm_iteration'] == 6)]
safb_df = safb_df.groupby(['gpt_model', 'target_character']).agg({'Evaluation/acc_imp_perc': ['mean']})
safb_df.columns = ['+ Feedback & Self-Alignment']
safb_df = safb_df.reset_index()
safb_df

  gpt_model  target_character  + Feedback & Self-Alignment
0    gpt-4o                 1                     0.088889
1    gpt-4o                 2                     0.133951

In [351]:
safb_df_cp = safb_df.copy()
safb_df_cp['gpt_model'] = 'chatgpt-4o'
safb_df_cp['+ Feedback & Self-Alignment'] = 0
safb_df = pd.concat([safb_df, safb_df_cp])
safb_df

    gpt_model  target_character  + Feedback & Self-Alignment
0      gpt-4o                 1                     0.088889
1      gpt-4o                 2                     0.133951
0  chatgpt-4o                 1                     0.000000
1  chatgpt-4o                 2                     0.000000

In [352]:
pk = ['gpt_model', 'target_character']

merged = pd.merge(base_df, sa_df, on=pk).merge(fb_df, on=pk).merge(safb_df, on=pk)
merged

,gpt_model,pe,target_character,Base,+ Self-Alignment,+ Feedback,+ Feedback & Self-Alignment
0,chatgpt-4o,cot,1,0.002222,0.000000,0.076190,0.000000
1,chatgpt-4o,cot,2,0.411111,0.000000,0.327778,0.000000
2,chatgpt-4o,got,1,0.258333,0.000000,0.076190,0.000000
3,chatgpt-4o,got,2,0.648889,0.000000,0.327778,0.000000
4,chatgpt-4o,tot,1,0.235556,0.000000,0.076190,0.000000
5,chatgpt-4o,tot,2,0.393333,0.000000,0.327778,0.000000
6,gpt-4o,cot,1,0.085185,0.069841,0.094643,0.088889
7,gpt-4o,cot,2,0.101111,0.025926,0.136059,0.133951
8,gpt-4o,got,1,0.035043,0.069841,0.094643,0.088889
9,gpt-4o,got,2,0.056566,0.025926,0.136059,0.133951
10,gpt-4o,tot,1,0.050427,0.069841,0.094643,0.088889
11,gpt-4o,tot,2,0.068519,0.025926,0.136059,0.133951

In [353]:
mean = merged.groupby('gpt_model').agg({'Base': ['mean'], '+ Self-Alignment': ['mean'], '+ Feedback': ['mean'], '+ Feedback & Self-Alignment': ['mean']})
mean.columns = ['Base', '+ Self-Alignment', '+ Feedback', '+ Feedback & Self-Alignment']
mean.insert(0, 'pe', 'mean')
mean.insert(0, 'target_character', 'mean')
mean = mean.reset_index()
mean

,gpt_model,target_character,pe,Base,+ Self-Alignment,+ Feedback,+ Feedback & Self-Alignment
0,chatgpt-4o,mean,mean,0.324907,0.000000,0.201984,0.00000
1,gpt-4o,mean,mean,0.066142,0.047884,0.115351,0.11142

In [354]:
result = pd.concat([mean, merged])
result

,gpt_model,target_character,pe,Base,+ Self-Alignment,+ Feedback,+ Feedback & Self-Alignment
0,chatgpt-4o,mean,mean,0.324907,0.000000,0.201984,0.000000
1,gpt-4o,mean,mean,0.066142,0.047884,0.115351,0.111420
0,chatgpt-4o,1,cot,0.002222,0.000000,0.076190,0.000000
1,chatgpt-4o,2,cot,0.411111,0.000000,0.327778,0.000000
2,chatgpt-4o,1,got,0.258333,0.000000,0.076190,0.000000
3,chatgpt-4o,2,got,0.648889,0.000000,0.327778,0.000000
4,chatgpt-4o,1,tot,0.235556,0.000000,0.076190,0.000000
5,chatgpt-4o,2,tot,0.393333,0.000000,0.327778,0.000000
6,gpt-4o,1,cot,0.085185,0.069841,0.094643,0.088889
7,gpt-4o,2,cot,0.101111,0.025926,0.136059,0.133951
8,gpt-4o,1,got,0.035043,0.069841,0.094643,0.088889
9,gpt-4o,2,got,0.056566,0.025926,0.136059,0.133951
10,gpt-4o,1,tot,0.050427,0.069841,0.094643,0.088889
11,gpt-4o,2,tot,0.068519,0.025926,0.136059,0.133951

In [355]:
result.to_csv('self-alignment-and-feedback.csv', index=False)

In [356]:

target_character_order = [1, 2, "mean"]  # 예: 특정 시나리오 번호와 "mean"
pe_order = ["cot", "tot", "got", "mean"]  # 예: Prompt Engineering 방식

result['target_character'] = pd.Categorical(result['target_character'], categories=target_character_order, ordered=True)
result['pe'] = pd.Categorical(result['pe'], categories=pe_order, ordered=True)


pivot_df = result.pivot_table(index=['target_character', 'pe'], columns='gpt_model', values=['Base', '+ Self-Alignment', '+ Feedback', '+ Feedback & Self-Alignment'])
pivot_df

/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_67800/2994687191.py:8: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_df = result.pivot_table(index=['target_character', 'pe'], columns='gpt_model', values=['Base', '+ Self-Alignment', '+ Feedback', '+ Feedback & Self-Alignment'])

                      + Feedback           + Feedback & Self-Alignment  \
gpt_model             chatgpt-4o    gpt-4o                  chatgpt-4o
target_character pe
1                cot    0.076190  0.094643                         0.0
                 tot    0.076190  0.094643                         0.0
                 got    0.076190  0.094643                         0.0
2                cot    0.327778  0.136059                         0.0
                 tot    0.327778  0.136059                         0.0
                 got    0.327778  0.136059                         0.0
mean             mean   0.201984  0.115351                         0.0

                                + Self-Alignment                 Base  \
gpt_model                gpt-4o       chatgpt-4o    gpt-4o chatgpt-4o
target_character pe
1                cot   0.088889              0.0  0.069841   0.002222
                 tot   0.088889              0.0  0.069841   0.235556
                 got   0.088889              0.0  0.069841   0.258333
2                cot   0.133951              0.0  0.025926   0.411111
                 tot   0.133951              0.0  0.025926   0.393333
                 got   0.133951              0.0  0.025926   0.648889
mean             mean  0.111420              0.0  0.047884   0.324907


gpt_model                gpt-4o
target_character pe
1                cot   0.085185
                 tot   0.050427
                 got   0.035043
2                cot   0.101111
                 tot   0.068519
                 got   0.056566
mean             mean  0.066142

In [357]:
pivot_df.columns = pivot_df.columns.swaplevel(0, 1)
pivot_df.columns

MultiIndex([('chatgpt-4o',                  '+ Feedback'),
            (    'gpt-4o',                  '+ Feedback'),
            ('chatgpt-4o', '+ Feedback & Self-Alignment'),
            (    'gpt-4o', '+ Feedback & Self-Alignment'),
            ('chatgpt-4o',            '+ Self-Alignment'),
            (    'gpt-4o',            '+ Self-Alignment'),
            ('chatgpt-4o',                        'Base'),
            (    'gpt-4o',                        'Base')],
           names=['gpt_model', None])

In [359]:
# 정렬 (주어진 Categorical 순서가 반영됨)
pivot_df = pivot_df.sort_index(level=['target_character', 'pe'], sort_remaining=False)

column_order = [
            (    'gpt-4o',                        'Base'),
            (    'gpt-4o',            '+ Self-Alignment'),
            (    'gpt-4o',                  '+ Feedback'),
            (    'gpt-4o', '+ Feedback & Self-Alignment'),
            (    'chatgpt-4o',                    'Base'),
            (    'chatgpt-4o',            '+ Self-Alignment'),
            (    'chatgpt-4o',                  '+ Feedback'),
            (    'chatgpt-4o', '+ Feedback & Self-Alignment')
]

# 결과 확인
pivot_df = pivot_df[column_order]
pivot_df

gpt_model                gpt-4o                              \
                           Base + Self-Alignment + Feedback
target_character pe
1                cot   0.085185         0.069841   0.094643
                 tot   0.050427         0.069841   0.094643
                 got   0.035043         0.069841   0.094643
2                cot   0.101111         0.025926   0.136059
                 tot   0.068519         0.025926   0.136059
                 got   0.056566         0.025926   0.136059
mean             mean  0.066142         0.047884   0.115351

gpt_model                                         chatgpt-4o                   \
                      + Feedback & Self-Alignment       Base + Self-Alignment
target_character pe
1                cot                     0.088889   0.002222              0.0
                 tot                     0.088889   0.235556              0.0
                 got                     0.088889   0.258333              0.0
2                cot                     0.133951   0.411111              0.0
                 tot                     0.133951   0.393333              0.0
                 got                     0.133951   0.648889              0.0
mean             mean                    0.111420   0.324907              0.0

gpt_model
                      + Feedback + Feedback & Self-Alignment
target_character pe
1                cot    0.076190                         0.0
                 tot    0.076190                         0.0
                 got    0.076190                         0.0
2                cot    0.327778                         0.0
                 tot    0.327778                         0.0
                 got    0.327778                         0.0
mean             mean   0.201984                         0.0

In [372]:
def insert_str(src_str, idx, insert_str):
    # LaTeX 문자열을 줄 단위로 나눔
    lines = src_str.splitlines()
    
    # 지정된 줄 번호 뒤에 \midrule 삽입
    lines.insert(idx, insert_str)
    
    # 다시 LaTeX 문자열로 결합
    return "\n".join(lines)

In [415]:
from IPython.display import display, Latex


tex_str = pivot_df.to_latex(buf=None, escape=True, bold_rows=False, position='!t', float_format="%.3f", multicolumn_format='c',
                            caption='Ablation study results for framework architecture, comparing accuracy across prompt engineering methods and scenarios.', label='tab:result_pe')

tex_str = tex_str.replace('target_character', 'Scenario')
tex_str = tex_str.replace('& pe &', '& PE &')
tex_str = tex_str.replace('gpt_model', '')
tex_str = tex_str.replace('table', 'table*')
tex_str = tex_str.replace('Self-Alignment', 'SA')
tex_str = tex_str.replace('Feedback', 'FB')
tex_str = tex_str.replace('\cline{1-10}\n', '')
tex_str = tex_str.replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT')
tex_str = tex_str.replace('mean & mean', '\\multicolumn{2}{c|}{\\textbf{Mean}}')
tex_str = tex_str.replace('\multicolumn{4}{c}{gpt-4o}', '\multicolumn{4}{c}{\\texttt{gpt-4o-2024-08-06}}')
original_header = ' &  & Base & + SA & + FB & + FB \\& SA & Base & + SA & + FB & + FB \\& SA \\\\'
modified_header = original_header.replace(
    'Base', '\\textbf{Base}'
).replace(
    '+ SA', '\\textbf{+SA}'
).replace(
    '+ FB \\& SA', '\\textbf{+FB, SA}'
).replace(
    '+ FB', '\\textbf{+FB}'
)

# 기존 문자열에서 헤더 교체
tex_str = tex_str.replace(original_header, modified_header)

tex_str = tex_str.replace('\\begin{tabular}{llrrrrrrrr}', '\\begin{tabular}{ll|rrrr|rrrr}')

tex_str = tex_str.replace('chatgpt-4o', '\\texttt{chatgpt-4o-latest} (Dec 2024)')

tabular_header = "\\begin{tabular}{p{1.5cm}p{1.5cm}|p{1.3cm}p{1.3cm}p{1.3cm}p{1.3cm}|p{1.3cm}p{1.3cm}p{1.3cm}p{1.3cm}}"
# 기존 header를 새 header로 교체
tex_str = tex_str.replace("\\begin{tabular}{ll|rrrr|rrrr}", tabular_header)


offset = 0
tex_str = insert_str(tex_str, offset + 12, "\\midrule")
from IPython.display import display, Latex

tex_str = pivot_df.to_latex(buf=None, escape=True, bold_rows=False, position='!t', float_format="%.3f",
                            multicolumn_format='c',
                            caption='Ablation study results for framework architecture, comparing accuracy across prompt engineering methods and scenarios.',
                            label='tab:result_pe')

tex_str = tex_str.replace('target_character', 'Scenario')
tex_str = tex_str.replace('& pe &', '& PE &')
tex_str = tex_str.replace('gpt_model', '')
tex_str = tex_str.replace('table', 'table*')
tex_str = tex_str.replace('Self-Alignment', 'SA')
tex_str = tex_str.replace('Feedback', 'FB')
tex_str = tex_str.replace('\cline{1-10}\n', '')
tex_str = tex_str.replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT')
tex_str = tex_str.replace('mean & mean', '\\multicolumn{2}{c|}{\\textbf{Mean}}')
tex_str = tex_str.replace('\multicolumn{4}{c}{gpt-4o}', '\multicolumn{4}{c}{\\texttt{gpt-4o-2024-08-06}}')
original_header = ' &  & Base & + SA & + FB & + FB \\& SA & Base & + SA & + FB & + FB \\& SA \\\\'
modified_header = original_header.replace(
    'Base', '\\textbf{Base}'
).replace(
    '+ SA', '\\textbf{+SA}'
).replace(
    '+ FB \\& SA', '\\textbf{+FB, SA}'
).replace(
    '+ FB', '\\textbf{+FB}'
)
tex_str = tex_str.replace('{c}{\\texttt{gpt-4o-2024-08-06}', '{c|}{\\texttt{gpt-4o-2024-08-06}')

# 기존 문자열에서 헤더 교체
tex_str = tex_str.replace(original_header, modified_header)

tex_str = tex_str.replace('\\begin{tabular}{llrrrrrrrr}', '\\begin{tabular}{ll|rrrr|rrrr}')
tex_str = tex_str.replace('chatgpt-4o', '\\texttt{chatgpt-4o-latest} (Dec 2024)')

tabular_header = "\\begin{tabular}{p{1.5cm}p{1.5cm}|p{1.3cm}p{1.3cm}p{1.3cm}p{1.3cm}|p{1.3cm}p{1.3cm}p{1.3cm}p{1.3cm}}"
# 기존 header를 새 header로 교체
tex_str = tex_str.replace("\\begin{tabular}{ll|rrrr|rrrr}", tabular_header)

offset = 0
tex_str = insert_str(tex_str, offset + 12, "\\midrule")
offset += 1
tex_str = insert_str(tex_str, offset + 15, "\\midrule")
offset += 1


with open('self-alignment-and-feedback.tex', 'w') as f:
    f.write(tex_str)
display(Latex(tex_str))

display(Latex(tex_str))